# PCFG production probabilities
S_probability = 1.0

NP_probability = {
    "John": 0.6,
    "Mary": 0.4
}

VP_probability = {
    "runs": 0.5,
    "walks": 0.5
}
def sentence_probability(sentence):
    """
    Calculate the probability of a two-word
    sentence using the given PCFG.
    """

    words = sentence.strip().split()

    # Sentence must contain exactly two words
    if len(words) != 2:
        return 0.0

    subject = words[0]
    verb = words[1]

    # Check whether subject and verb
    # can be generated by the grammar
    if subject not in NP_probability:
        return 0.0

    if verb not in VP_probability:
        return 0.0

    # Calculate:
    # P(S) * P(NP) * P(VP)

    probability = (
        S_probability
        * NP_probability[subject]
        * VP_probability[verb]
    )

    return probability


# Main program
print("======================================")
print(" PCFG SENTENCE PROBABILITY")
print("======================================")

sentence = input("Enter a two-word sentence: ")

probability = sentence_probability(sentence)

print("\nSentence:", sentence)
print("Probability:", f"{probability:.2f}")